ALTER TABLE coding_sessions
    ADD COLUMN IF NOT EXISTS timed_mode BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS duration_minutes INTEGER,
    ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP;
